
name: 🚀 Deploy to environment production
on: 
    push:
        branches:
            - main
jobs:
  web-deploy:
    name: 🎉 FTP-Deploy-Production
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER_PROD }}
        username: ${{ secrets.FTP_USERNAME_PROD }}
        password: ${{ secrets.FTP_PASSWORD_PROD }}

    if: github.ref == 'refs/heads/main'